[package]
name = "evac"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
authors = ["Khionu Sybiern <dev@khionu.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
